#!/bin/bash

if [ -z $1 ]; then
	echo "Ip address is required as a first argument / Second argument is optional (bucket)"
	exit
fi 

DATE=$(date +%Y%m%d%H%M)
COUNTER=0
mkdir /tmp/backup_couchbase


if [ -z $2 ]; then
	for i in `curl http://$1:8091/pools/default/buckets 2> /dev/null | python -mjson.tool | grep -v 'hostname' | grep 'name' | awk -F\" '{print \$4}'` ; do	
		echo "Backing up $i"
		/usr/bin/curl 'http://localhost:8092/$i/_all_docs' > /tmp/backup_tmp 
		python /opt/backup-scripts/backup_memc.py -a $1:8091 -b $i -f /tmp/backup_tmp -o /tmp/backup_couchbase/backup_$i
	done
else
	echo "Backing up $2"
        /usr/bin/curl 'http://localhost:8092/$2/_all_docs' > /tmp/backup_tmp
        python /opt/backup-scripts/backup_memc.py -a $1:8091 -b $2 -f /tmp/backup_tmp -o /tmp/backup_couchbase/backup_$2
fi


#packaging data
tar cfz /tmp/backup_$DATE.tar.gz /tmp/backup_couchbase/

#cleaning up
rm -rf /tmp/backup_couchbase
rm /tmp/backup_tmp

#Done
echo 'Backup done'
